title: Changes and Phases
author: Elizandtech
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Blog of states I call home, enjoyment of National Parks and my attempts to improve my time management skills.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
