title: Changes and Phases
author: Elizandtech
email: your-email@domain.com
markdown: kramdown
description: > # this means to ignore newlines until "baseurl:"
Blog of states I call home and my enjoyment of National Parks.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
